apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-weights
  namespace: llm-inference
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: lustre
  resources:
    requests:
      storage: 100Gi  # Adjust based on your model size requirements 