apiVersion: v1
kind: Service
metadata:
  name: chainlit-ui
  namespace: llm-inference
spec:
  selector:
    app: chainlit-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7860
  type: LoadBalancer 