apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-server
  namespace: llm-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-server
  template:
    metadata:
      labels:
        app: vllm-server
    spec:
      containers:
      - name: vllm
        image: ghcr.io/vllm-project/vllm:latest
        command: ["python", "-m", "vllm.entrypoints.openai.api_server"]
        args:
          - "--model=meta-llama/Llama-2-7b-chat-hf"
          - "--tensor-parallel-size=1"
          - "--gpu-memory-utilization=0.90"
          - "--max-model-len=8192"
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
            memory: "32Gi"
            cpu: "8"
        volumeMounts:
        - name: model-weights
          mountPath: /models
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: token
      volumes:
      - name: model-weights
        persistentVolumeClaim:
          claimName: model-weights 