apiVersion: v1
kind: Service
metadata:
  name: vllm-gemma
  namespace: llm-inference
spec:
  selector:
    app: vllm-gemma
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP 