apiVersion: v1
kind: Service
metadata:
  name: vllm-server
  namespace: llm-inference
spec:
  selector:
    app: vllm-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP 